### ISSUE TITLE
Repo crawler fails with BadMethodCallException

### ISSUE THREAD

**Issue by imphil** [librecores/librecores-web#331]
```
Apr 25 10:17:11 librecores php[9247]: 10:17:11 INFO      [app] Fetching commits for the repository 1 of project openrisc/mor1kx
Apr 25 10:17:11 librecores php[9247]: 10:17:11 ERROR     [app] Processing of repository resulted in an BadMethodCallException
Apr 25 10:17:11 librecores php[9247]: 10:17:11 ERROR     [app] Message: Undefined method 'getLatestCommit'. The method name must start with either findBy, findOneBy or countBy!
Apr 25 10:17:11 librecores php[9247]: 10:17:11 ERROR     [app] Trace: #0 /var/www/lc/site/src/Librecores/ProjectRepoBundle/RepoCrawler/GitRepoCrawler.php(154): Doctrine\ORM\EntityRepository
Apr 25 10:17:11 librecores php[9247]: #1 /var/www/lc/site/src/Librecores/ProjectRepoBundle/Consumer/UpdateProjectInformation.php(78): Librecores\ProjectRepoBundle\RepoCrawler\GitRepoCrawler
Apr 25 10:17:11 librecores php[9247]: #2 [internal function]: Librecores\ProjectRepoBundle\Consumer\UpdateProjectInformation->execute(Object(PhpAmqpLib\Message\AMQPMessage))
Apr 25 10:17:11 librecores php[9247]: #3 /var/www/lc/site/vendor/php-amqplib/rabbitmq-bundle/RabbitMq/Consumer.php(133): call_user_func(Array, Object(PhpAmqpLib\Message\AMQPMessage))
Apr 25 10:17:11 librecores php[9247]: #4 /var/www/lc/site/vendor/php-amqplib/rabbitmq-bundle/RabbitMq/Consumer.php(179): OldSound\RabbitMqBundle\RabbitMq\Consumer->processMessageQueueCallba
Apr 25 10:17:11 librecores php[9247]: #5 [internal function]: OldSound\RabbitMqBundle\RabbitMq\Consumer->processMessage(Object(PhpAmqpLib\Message\AMQPMessage))
Apr 25 10:17:11 librecores php[9247]: #6 /var/www/lc/site/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php(1040): call_user_func(Array, Object(PhpAmqpLib\Message\AMQPMessag
Apr 25 10:17:11 librecores php[9247]: #7 [internal function]: PhpAmqpLib\Channel\AMQPChannel->basic_deliver(Object(PhpAmqpLib\Wire\AMQPReader), Object(PhpAmqpLib\Message\AMQPMessage))
Apr 25 10:17:11 librecores php[9247]: #8 /var/www/lc/site/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(218): call_user_func(Array, Object(PhpAmqpLib\Wire\AMQPReader
Apr 25 10:17:11 librecores php[9247]: #9 /var/www/lc/site/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(373): PhpAmqpLib\Channel\AbstractChannel->dispatch('60,60', '
Apr 25 10:17:11 librecores php[9247]: #10 /var/www/lc/site/vendor/php-amqplib/rabbitmq-bundle/RabbitMq/Consumer.php(88): PhpAmqpLib\Channel\AbstractChannel->wait(NULL, false, 0)
Apr 25 10:17:11 librecores php[9247]: #11 /var/www/lc/site/vendor/php-amqplib/rabbitmq-bundle/Command/BaseConsumerCommand.php(90): OldSound\RabbitMqBundle\RabbitMq\Consumer->consume('250')
Apr 25 10:17:11 librecores php[9247]: #12 /var/www/lc/site/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php(255): OldSound\RabbitMqBundle\Command\BaseConsumerCommand
Apr 25 10:17:11 librecores php[9247]: #13 /var/www/lc/site/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(978): Symfony\Component\Console\Command\Command->run(Object(S
Apr 25 10:17:11 librecores php[9247]: #14 /var/www/lc/site/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(86): Symfony\Component\Console\Application->doRu
Apr 25 10:17:11 librecores php[9247]: #15 /var/www/lc/site/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(255): Symfony\Bundle\FrameworkBundle\Console\Application->doR
Apr 25 10:17:11 librecores php[9247]: #16 /var/www/lc/site/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(74): Symfony\Component\Console\Application->doRu
Apr 25 10:17:11 librecores php[9247]: #17 /var/www/lc/site/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(148): Symfony\Bundle\FrameworkBundle\Console\Application->doR
Apr 25 10:17:11 librecores php[9247]: #18 /var/www/lc/site/bin/console(26): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput))
Apr 25 10:17:11 librecores php[9247]: #19 {main}
```

**Comment by imphil** [comment]
This code has not really changed recently:

```php
$commitRepository = $this->manager->getRepository(Commit::class);
$lastCommit = $commitRepository->getLatestCommit($this->repo);
```

The exception message indicates we're hitting `EntityRepository::__call()` (see https://github.com/doctrine/orm/blob/master/lib/Doctrine/ORM/EntityRepository.php#L175). We actually shouldn't reach that code if we are inside `CommitRepository`, so maybe the service isn't properly registered any more?

@agathver could you have a look at that?

**Comment by agathver** [comment]
We need to migrate all usages into `getRepository` to use auto-wiring. It appears that the repository classes inheriting from `ServiceEntityRepository` are not properly registered with Doctrine.
